---
title: "Gene expression project"
subtitle: "Analysis script"
author: "Bernice Sepers & Ane Liv Berthelsen"

format:
  html: 
  #pdf: 
    papersize: "a4paper"
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    number-sections: FALSE
    documentclass: article
    geometry:
      - inner=3cm
      - outer=3cm
      - top=2cm
      - bottom=3cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    fig-pos: 'h'
    fig-cap-location: bottom
    tbl-cap-location: top
editor: visual
date: 11/20/2023
mainfont: Times New Roman
---

```{r}
#install.packages("here")
#install.packages("pacman")
#library(here)
here::here()
```

```{r}
#| label: packages
#| echo: FALSE
#here::here()
invisible(pacman::p_load(dplyr, tidyverse, cowplot, edgeR, DESeq2, RColorBrewer, ggplot2, reshape2))
#cowplot for toggling with plots
#edgeR  loads limma as a dependency, limma for annalysing microassay and RNA seq data
#DESeq2 needed for rowCounts
#reshape2 needed for the first plot
```

# Data

```{r}
#| label: load_data
#| echo: FALSE
#Load in the filtered data
#Mutate all needed predictors into factors
d_n<-readRDS("rnaseq_filtered_Liv.Rdata")  
d_n$samples$life_history_stage <- as.factor(d_n$samples$life_history_stage)
d_n$samples$colony <- as.factor(d_n$samples$colony)
d_n$samples$ID <- as.factor(d_n$samples$ID)
d_n$samples$year <- as.factor(d_n$samples$year)
d_n$samples$group <- as.factor(d_n$samples$group)
d_n$samples$pair <- as.factor(d_n$samples$pair)
#dim(d_n) 12639 rows
```

# Gene expression and inbreeding

```{r}
#Load in froh data
inbreeding <- read.csv("genetic_data.csv", header = TRUE, sep = ",")

# View the first few rows
head(inbreeding)

#Bind by ID
d_n$samples <- left_join(d_n$samples, inbreeding, by = "ID")
#check <- subset(d_n$samples, select = c("ID", "froh.new")) #is complete
#check that dimensions are equal
#dim(d_n)  # Should return (genes x samples)
#dim(design_inbreeding)  # Should return (samples x predictors)
```

### Run limma model with froh

```{r}
#Limma model with continuous variable fROH
#Create a design matrix including fROH
design_inbreeding <- model.matrix(~ froh.new, data = d_n$samples)  #Keep intercept, as we would otherwise assume that all genes have an expression of 0 at froh = 0 (https://support.bioconductor.org/p/121084/)

# #voom() converts the read counts to log2-cpm, with associated weights, ready for linear modelling
vobj_inbreeding <- voom(d_n, design_inbreeding, plot=TRUE)

#Fit a random effect
dupcor_inbreeding <- duplicateCorrelation(vobj_inbreeding, design_inbreeding, block = d_n$samples$ID)
# #dupcor_inbreeding$consensus #the estimated intra individual correlation (0.196295)

vobj_inbreeding = voom(d_n, design_inbreeding, plot=TRUE, 
                        block=d_n$samples$ID, correlation=dupcor_inbreeding$consensus)
# #update the correlation for the new voom weights
dupcor_inbreeding <- duplicateCorrelation(vobj_inbreeding, design_inbreeding, block = d_n$samples$ID)
# #dupcor_inbreeding$consensus #the estimated intra individual correlation (0.1962937)

#Estimate linear mixed model with a single variance component
vfit_inbreeding <- lmFit(vobj_inbreeding, design_inbreeding, block=d_n$samples$ID, correlation=dupcor_inbreeding$consensus)

efit_inbreeding <- eBayes(vfit_inbreeding)
topTable(efit_inbreeding, n=20)
plotSA(efit_inbreeding, main="Final model: Mean-variance trend")
plotMD(efit_inbreeding)
abline(h=0,col="darkgrey")

#adjusted p-value cutoff that is set at 5% by default.
efit_inbreeding$F
#head(efit_inbreeding$F.p.value) #pval of the moderated F-statistics (equivalent to one-way ANOVA), it combines all contrast, so in this case it is the same as the t-statistic
#head(efit_inbreeding$p.value) #same
summary(decideTests(efit_inbreeding, adjust.method="fdr"))

tfit_inbreeding <- treat(vfit_inbreeding, lfc=lfc_half) 
topTreat(tfit_inbreeding)
nrow(tfit_inbreeding)
dt_inbreeding <- decideTests(tfit_inbreeding, adjust.method="fdr")
summary(dt_inbreeding) #no differential expressed genes related to froh
```
