---
title: "Gene expression project"
subtitle: "Analysis script"
author: "Bernice Sepers & Ane Liv Berthelsen"

format:
  html: 
  #pdf: 
    papersize: "a4paper"
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    number-sections: FALSE
    documentclass: article
    geometry:
      - inner=3cm
      - outer=3cm
      - top=2cm
      - bottom=3cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    fig-pos: 'h'
    fig-cap-location: bottom
    tbl-cap-location: top
editor: visual
date: 11/20/2023
mainfont: Times New Roman
---

```{r}
#install.packages("here")
#install.packages("pacman")
#library(here)
here::here()
```

```{r}
#| label: packages
#| echo: FALSE
#here::here()
invisible(pacman::p_load(dplyr, tidyverse, cowplot, edgeR, DESeq2, RColorBrewer, ggplot2, reshape2))
#cowplot for toggling with plots
#edgeR  loads limma as a dependency, limma for annalysing microassay and RNA seq data
#DESeq2 needed for rowCounts
#reshape2 needed for the first plot
```

# Data 

```{r}
#| label: load_data
#| echo: FALSE
#Load in the filtered data
#Mutate all needed predictors into factors
d_n<-readRDS("rnaseq_filtered_Liv.Rdata")  
d_n$samples$life_history_stage <- as.factor(d_n$samples$life_history_stage)
d_n$samples$colony <- as.factor(d_n$samples$colony)
d_n$samples$ID <- as.factor(d_n$samples$ID)
d_n$samples$year <- as.factor(d_n$samples$year)
d_n$samples$group <- as.factor(d_n$samples$group)
d_n$samples$pair <- as.factor(d_n$samples$pair)
#dim(d_n) 12639 rows
```

#Visualize data

```{r}
#| label: visualize_data
#| echo: FALSE
counts_per_million <- cpm(d_n)
log_counts_per_million <- cpm(d_n, log = T)
#Calculate mean and median value
L <- mean(d_n$samples$lib.size) * 1e-6 #average library size in millions
M <- median(d_n$samples$lib.size) * 1e-6 
#c(L, M) #19.65813, 19.10705
lcpm.cutoff <- log2(10/M + 2/L) #-0.677827

df_long <- data.frame(log_counts_per_million)
df_long$Gene <- rownames(df_long)
df_melted <- melt(df_long, id.vars = "Gene", variable.name = "Sample", value.name = "LogCPM")

#costum color palette
palette_200 <- colorRampPalette(brewer.pal(12, "Paired"))(200)

density_plot <- ggplot(df_melted, aes(x = LogCPM, color = Sample)) +
  geom_density(size = 0.5) + 
  scale_color_manual(values = palette_200) + 
  geom_vline(xintercept = lcpm.cutoff, linetype = "dashed", color = "black") +  # Add cutoff line
  labs(title = "Filtered Data", x = "Log-cpm", y = "Density") +
  theme_classic() +
  theme(legend.position = "none") +
  ylim(0,0.20)

density_plot

# Save the density plot as a PNG file
ggsave(here::here("Plots","density_plot.png"), plot = density_plot, width = 12, height = 8, dpi = 600)

#Remove elements not used in the rest of the script
rm(counts_per_million, density_plot, df_long, df_melted, log_counts_per_million, L, M, lcpm.cutoff, palette_200)
```
# Differential gene expression analysis

```{r}
clrs <- c("Upregulated" = "plum3", "Downregulated" = "cornflowerblue", "Not Significant" = "grey20")
lfc <- 1 #log fold change of 1 is pretty standard but explore further
#a doubling in the original scaling is equal to a log2 fold change of 1
#a quadrupling is equal to a log2 fold change of 2
lfc_half <- 0.5
adj.P.value <- 0.05
```


## Time point: Analysis by Bernice
An example analysis where Bernice assessed differential expression per gene between the two time points (start vs end).

```{r}
##-------------- ANALYSIS OF TIME POINT --------------##
#Tagged out to not run dupcor again (the saved outcome can be called from the dupcor folder)
# design <- model.matrix(~ -1 + group, data = d_n$samples) #setting up model contrasts is more straight forward in the absence of an intercept for timepoint
# contr.matrix <- makeContrasts(
#  end_vs_start = group2-group1,
#  levels = colnames(design)) #create matrix for contrasts
# # Use voom to remove variance dependency on mean, see https://bioconductor.org/packages/release/workflows/vignettes/RNAseq123/inst/doc/limmaWorkflow.html
# # voom converts raw counts to log-CPM values by automatically extracting library sizes and normalisation factors from d itself. 
# #  If filtering of lowly-expressed genes is insufficient, a drop in variance levels can be observed at the low end of the expression scale due to very small counts.
# #voom() converts the read counts to log2-cpm, with associated weights, ready for linear modelling
# vobj_tmp <- voom(d_n, design, plot=TRUE)
#
# # Fit a random effect
# dupcor_tp <- duplicateCorrelation(vobj_tmp, design, block = d_n$samples$ID)
# dupcor_tp$consensus #the estimated intra individual correlation (0.2988794)
# #the intra individual correlation will change the voom weights slightly
# #run voom again considering the duplicateCorrelation results in order to compute more accurate precision weights
# vobj = voom(d_n, design, plot=TRUE, 
#            block=d_n$samples$ID, correlation=dupcor_tp$consensus)
# #update the correlation for the new voom weights
# dupcor_tp <- duplicateCorrelation(vobj, design, block = d_n$samples$ID)
# dupcor_tp$consensus #the estimated intra individual correlation (0.2989905)
#
# #save dupcor_tp
# saveRDS(dupcor_tp, file = here::here("Dupcor","dupcor_tp.rds"))


#Load dupcor_tp
dupcor_tp <- readRDS(here::here("Dupcor","dupcor_tp.rds"))

#analyzing repeated measures data using duplicateCorrelation.
#The model forces the magnitude of the random effect to be the same across all genes.
# Estimate linear mixed model with a single variance component
# Fit the model for each gene
# But this step uses only the genome-wide average for the random effect
vfit <- lmFit(vobj, design, block=d_n$samples$ID, correlation=dupcor_tp$consensus)
vfit <- contrasts.fit(vfit, contrasts=contr.matrix)
# Fit Empirical Bayes for moderated t-statistics, empirical Bayes moderation is carried out by borrowing information across all the genes to obtain more precise estimates of gene-wise variability
efit <- eBayes(vfit)
topTable(efit, n=20)
plotSA(efit, main="Final model: Mean-variance trend")
plotMD(efit)
abline(h=0,col="darkgrey")

#adjusted p-value cutoff that is set at 5% by default.
efit$F
head(efit$F.p.value) #pval of the moderated F-statistics (equivalent to one-way ANOVA), it combines all contrast, so in this case it is the same as the t-statistic
head(efit$p.value) #same
summary(decideTests(efit, adjust.method="fdr"))
#set log-fold-changes (log-FCs) to be above a minimum value. The treat method (McCarthy and Smyth 2009) used to calculate p-values from empirical Bayes moderated t-statistics with a minimum log-FC requirement. 
#no need to use the ebayes output for this
#lfc<-0.14 #threshold set by Bernice to differentiate between differentially expressed genes

tfit <- treat(vfit, lfc=lfc) #lfc = 1, lfc_half = 0.5
topTreat(tfit)
nrow(tfit)
dt <- decideTests(tfit, adjust.method="fdr")
summary(dt) 

#Test for significance
Allgenes_tp <- as.data.frame(topTreat(tfit, n=nrow(tfit)))
Filteredgenes_tp <- subset(Allgenes_tp, abs(logFC) >= lfc & round(adj.P.Val, 2) < adj.P.value)
nrow(subset(Filteredgenes_tp, Filteredgenes_tp$logFC > 0))
nrow(subset(Filteredgenes_tp, Filteredgenes_tp$logFC < 0))

#Plot the outcome
Allgenes_tp$Significance <- "Not Significant"
Allgenes_tp$Significance[Allgenes_tp$adj.P.Val < adj.P.value & Allgenes_tp$logFC >= lfc] <- "Upregulated"
Allgenes_tp$Significance[Allgenes_tp$adj.P.Val < adj.P.value & Allgenes_tp$logFC <= lfc] <- "Downregulated"

#Plot DEG
tp_plot <- ggplot(Allgenes_tp, aes(x = AveExpr, y = logFC, color = Significance, size = Significance)) +
  geom_point() +
  scale_color_manual(values = clrs) +  
  scale_size_manual(values = c(1.5, 0.5, 1.5)) +
  labs(title = "End vs start", x = "Mean Expression (logCPM)", y = "Log Fold Change") +
  theme_classic() +
  theme(legend.position = "top")
```
## Life stages

```{r}
#Tagged out to not run dupcor again (the saved outcome can be called from the dupcor folder)
# #Create a design matrix
# design_lhs <- model.matrix(~ -1 + life_history_stage, data = d_n$samples) #model contrasts without intercept is easier
# colnames(design_lhs) <- gsub("life_history_stage", "", colnames(design_lhs)) #clean group names
#
# #create matrix for contrasts
# contr.matrix.lhs <- makeContrasts(
#   adultvspup = Mother-Pup,
#   levels = colnames(design_lhs)) 
#
# #voom() converts the read counts to log2-cpm, with associated weights, ready for linear modelling
# vobj_lhs <- voom(d_n, design_lhs, plot=TRUE)
# 
# # Fit a random effect
# dupcor_lhs <- duplicateCorrelation(vobj_lhs, design_lhs, block = d_n$samples$ID)
# #dupcor_lhs$consensus #the estimated intra individual correlation (0.13086)
# #the intra individual correlation will change the voom weights slightly
# #run voom again considering the duplicateCorrelation results in order to compute more accurate precision weights
# vobj_lhs = voom(d_n, design_lhs, plot=TRUE, 
#             block=d_n$samples$ID, correlation=dupcor_lhs$consensus)
# #update the correlation for the new voom weights
# dupcor_lhs <- duplicateCorrelation(vobj_lhs, design_lhs, block = d_n$samples$ID)
# #dupcor_lhs$consensus #the estimated intra individual correlation (0.1308769)
# 
# #save dupcor_lhs
# saveRDS(dupcor_lhs, file = here::here("Dupcor","dupcor_lhs.rds"))


#Load dupcor_lhs
dupcor_lhs <- readRDS(here::here("Dupcor","dupcor_lhs.rds"))

#Analyzing repeated measures data using duplicateCorrelation.
#The model forces the magnitude of the random effect to be the same across all genes.


#Estimate linear mixed model with a single variance component
vfit_lhs <- lmFit(vobj_lhs, design_lhs, block=d_n$samples$ID, correlation=dupcor_lhs$consensus)
vfit_lhs <- contrasts.fit(vfit_lhs, contrasts=contr.matrix.lhs)
# Fit Empirical Bayes for moderated t-statistics, empirical Bayes moderation is carried out by borrowing information across all the genes to obtain more precise estimates of gene-wise variability
efit_lhs <- eBayes(vfit_lhs)
topTable(efit_lhs, n=20)
plotSA(efit_lhs, main="Final model: Mean-variance trend")
plotMD(efit_lhs)
abline(h=0,col="darkgrey")

#adjusted p-value cutoff that is set at 5% by default.
efit_lhs$F
#head(efit_lhs$F.p.value) #pval of the moderated F-statistics (equivalent to one-way ANOVA), it combines all contrast, so in this case it is the same as the t-statistic
#head(efit_lhs$p.value) #same
summary(decideTests(efit_lhs, adjust.method="fdr"))
#set log-fold-changes (log-FCs) to be above a minimum value. The treat method (McCarthy and Smyth 2009) used to calculate p-values from empirical Bayes moderated t-statistics with a minimum log-FC requirement. 
#no need to use the ebayes output for this

#Positive values means the gene is more expressed
tfit_lhs <- treat(vfit_lhs, lfc=lfc) 
topTreat(tfit_lhs)
nrow(tfit_lhs)
dt_lhs <- decideTests(tfit_lhs, adjust.method="fdr")
summary(dt_lhs) 

#Test for significance
Allgenes_lhs <- as.data.frame(topTreat(tfit_lhs, n=nrow(tfit_lhs)))
Filteredgenes_lhs <- subset(Allgenes_lhs, abs(logFC) >= lfc & round(adj.P.Val, 2) < adj.P.value)
nrow(subset(Filteredgenes_lhs, Filteredgenes_lhs$logFC > 0))
nrow(subset(Filteredgenes_lhs, Filteredgenes_lhs$logFC < 0))

#Plot the outcome
Allgenes_lhs$Significance <- "Not Significant"
Allgenes_lhs$Significance[Allgenes_lhs$adj.P.Val < adj.P.value & Allgenes_lhs$logFC >= lfc] <- "Upregulated"
Allgenes_lhs$Significance[Allgenes_lhs$adj.P.Val < adj.P.value & Allgenes_lhs$logFC <= lfc] <- "Downregulated"

#Plot DEG
lhs_plot <- ggplot(Allgenes_lhs, aes(x = AveExpr, y = logFC, color = Significance, size = Significance)) +
  geom_point() +
  scale_color_manual(values = clrs) +  
  scale_size_manual(values = c(1.5, 0.5, 1.5)) +
  labs(title = "Adult vs pup", x = "Mean Expression (logCPM)", y = "Log Fold Change") +
  theme_classic() +
  theme(legend.position = "top")
```
## Colony

```{r}
#Tagged out to not run dupcor again (the saved outcome can be called from the dupcor folder)
# #Create a design matrix
# design_c <- model.matrix(~ -1 + colony, data = d_n$samples) #model contrasts without intercept is easier
# colnames(design_c) <- gsub("colony", "", colnames(design_c)) #clean group names
#
# #create matrix for contrasts
# contr.matrix.c <- makeContrasts(
#   SSBvsFWB = SSB-FWB,
#   levels = colnames(design_c)) 
#
# #voom() converts the read counts to log2-cpm, with associated weights, ready for linear modelling
# vobj_c <- voom(d_n, design_c, plot=TRUE)
#
# # Fit a random effect
# dupcor_c <- duplicateCorrelation(vobj_c, design_c, block = d_n$samples$ID)
# #dupcor_c$consensus #the estimated intra individual correlation (0.1938427)
# #the intra individual correlation will change the voom weights slightly
# #run voom again considering the duplicateCorrelation results in order to compute more accurate precision weights
# vobj_c = voom(d_n, design_c, plot=TRUE, 
#             block=d_n$samples$ID, correlation=dupcor_c$consensus)
# #update the correlation for the new voom weights
# dupcor_c <- duplicateCorrelation(vobj_c, design_c, block = d_n$samples$ID)
# #dupcor_c$consensus #the estimated intra individual correlation (0.1938511)
#
# #save dupcor_c
# saveRDS(dupcor_c, file = here::here("Dupcor","dupcor_c.rds"))


#Load dupcor_c
dupcor_c <- readRDS(here::here("Dupcor","dupcor_c.rds"))

#Analyzing repeated measures data using duplicateCorrelation.
#The model forces the magnitude of the random effect to be the same across all genes.

#Estimate linear mixed model with a single variance component
vfit_c <- lmFit(vobj_c, design_c, block=d_n$samples$ID, correlation=dupcor_c$consensus)
vfit_c <- contrasts.fit(vfit_c, contrasts=contr.matrix.c)
# Fit Empirical Bayes for moderated t-statistics, empirical Bayes moderation is carried out by borrowing information across all the genes to obtain more precise estimates of gene-wise variability
efit_c <- eBayes(vfit_c)
topTable(efit_c, n=20)
plotSA(efit_c, main="Final model: Mean-variance trend")
plotMD(efit_c)
abline(h=0,col="darkgrey")

#adjusted p-value cutoff that is set at 5% by default.
efit_c$F
#head(efit_c$F.p.value) #pval of the moderated F-statistics (equivalent to one-way ANOVA), it combines all contrast, so in this case it is the same as the t-statistic
#head(efit_c$p.value) #same
summary(decideTests(efit_c, adjust.method="fdr"))
#set log-fold-changes (log-FCs) to be above a minimum value. The treat method (McCarthy and Smyth 2009) used to calculate p-values from empirical Bayes moderated t-statistics with a minimum log-FC requirement. 
#no need to use the ebayes output for this

#Positive values means the gene is more expressed
tfit_c <- treat(vfit_c, lfc=lfc) 
topTreat(tfit_c)
nrow(tfit_c)
dt_c <- decideTests(tfit_c, adjust.method="fdr")
summary(dt_c) 

#Test for significance
Allgenes_c <- as.data.frame(topTreat(tfit_c, n=nrow(tfit_c)))
Filteredgenes_c <- subset(Allgenes_c, abs(logFC) >= lfc & round(adj.P.Val, 2) < adj.P.value)
nrow(subset(Filteredgenes_c, Filteredgenes_c$logFC > 0))
nrow(subset(Filteredgenes_c, Filteredgenes_c$logFC < 0))

#Plot the outcome
Allgenes_c$Significance <- "Not Significant"
Allgenes_c$Significance[Allgenes_c$adj.P.Val < adj.P.value & Allgenes_c$logFC >= lfc] <- "Upregulated"
Allgenes_c$Significance[Allgenes_c$adj.P.Val < adj.P.value & Allgenes_c$logFC <= lfc] <- "Downregulated"

#Plot DEG
c_plot <- ggplot(Allgenes_c, aes(x = AveExpr, y = logFC, color = Significance, size = Significance)) +
  geom_point() +
  scale_color_manual(values = clrs) +  
  scale_size_manual(values = 0.5) +
  labs(title = "SSB vs FWB", x = "Mean Expression (logCPM)", y = "Log Fold Change") +
  theme_classic() +
  theme(legend.position = "top")

```

## Season

```{r}
#Tagged out to not run dupcor again (the saved outcome can be called from the dupcor folder)
# #Create a design matrix
# design_y <- model.matrix(~ -1 + year, data = d_n$samples) #model contrasts without intercept is easier
# colnames(design_y) <- c("Season1", "Season2") #clean group names
# #create matrix for contrasts
# contr.matrix.y <- makeContrasts(
#   Season1vsSeason2 = Season1-Season2,
#   levels = colnames(design_y)) 
#
# #voom() converts the read counts to log2-cpm, with associated weights, ready for linear modelling
# vobj_y <- voom(d_n, design_y, plot=TRUE)
# 
# #Fit a random effect
# dupcor_y <- duplicateCorrelation(vobj_y, design_y, block = d_n$samples$ID)
# #dupcor_y$consensus #the estimated intra individual correlation (0.1672733)
# #the intra individual correlation will change the voom weights slightly
# #run voom again considering the duplicateCorrelation results in order to compute more accurate precision weights
# vobj_y = voom(d_n, design_y, plot=TRUE, 
#             block=d_n$samples$ID, correlation=dupcor_y$consensus)
# #update the correlation for the new voom weights
# dupcor_y <- duplicateCorrelation(vobj_y, design_y, block = d_n$samples$ID)
# #dupcor_y$consensus #the estimated intra individual correlation (0.1672867)
# 
# #save dupcor_y
# saveRDS(dupcor_y, file = here::here("Dupcor","dupcor_y.rds"))
#Load dupcor_y
dupcor_y <- readRDS(here::here("Dupcor","dupcor_y.rds"))


#Analyzing repeated measures data using duplicateCorrelation.
#The model forces the magnitude of the random effect to be the same across all genes.

#Estimate linear mixed model with a single variance component
vfit_y <- lmFit(vobj_y, design_y, block=d_n$samples$ID, correlation=dupcor_y$consensus)
vfit_y <- contrasts.fit(vfit_y, contrasts=contr.matrix.y)
# Fit Empirical Bayes for moderated t-statistics, empirical Bayes moderation is carried out by borrowing information across all the genes to obtain more precise estimates of gene-wise variability
efit_y <- eBayes(vfit_y)
topTable(efit_y, n=20)
plotSA(efit_y, main="Final model: Mean-variance trend")
plotMD(efit_y)
abline(h=0,col="darkgrey")

#adjusted p-value cutoff that is set at 5% by default.
efit_y$F
#head(efit_y$F.p.value) #pval of the moderated F-statistics (equivalent to one-way ANOVA), it combines all contrast, so in this case it is the same as the t-statistic
#head(efit_y$p.value) #same
summary(decideTests(efit_y, adjust.method="fdr"))
#set log-fold-changes (log-FCs) to be above a minimum value. The treat method (McCarthy and Smyth 2009) used to calculate p-values from empirical Bayes moderated t-statistics with a minimum log-FC requirement. 
#no need to use the ebayes output for this

tfit_y <- treat(vfit_y, lfc=lfc) 
topTreat(tfit_y)
nrow(tfit_y)
dt_y <- decideTests(tfit_y, adjust.method="fdr")
summary(dt_y) 

#Test for significance
Allgenes_y <- as.data.frame(topTreat(tfit_y, n=nrow(tfit_y)))
Filteredgenes_y <- subset(Allgenes_y, abs(logFC) >= lfc & round(adj.P.Val, 2) < adj.P.value)
nrow(subset(Filteredgenes_y, Filteredgenes_y$logFC > 0))
nrow(subset(Filteredgenes_y, Filteredgenes_y$logFC < 0))

#Plot the outcome
Allgenes_y$Significance <- "Not Significant"
Allgenes_y$Significance[Allgenes_y$adj.P.Val < adj.P.value & Allgenes_y$logFC >= lfc] <- "Upregulated"
Allgenes_y$Significance[Allgenes_y$adj.P.Val < adj.P.value & Allgenes_y$logFC <= lfc] <- "Downregulated"

#Plot DEG
y_plot <- ggplot(Allgenes_y, aes(x = AveExpr, y = logFC, color = Significance, size = Significance)) +
  geom_point() +
  scale_color_manual(values = clrs) +  
  scale_size_manual(values = 0.5) +
  labs(title = "2018-2019 vs 2019-2020", x = "Mean Expression (logCPM)", y = "Log Fold Change") +
  theme_classic() +
  theme(legend.position = "top")
```
```{r}
#Bind plots together
library(cowplot)

DEG_all <- plot_grid(y_plot, lhs_plot, c_plot, tp_plot)
ggsave(here::here("Plots","DEG_all.png"), plot = DEG_all, width = 12, height = 8, dpi = 600)
```

# Interactions

```{r}
#In this, we will test for interactions between life stage and season
#Both terms are used previously, so we do not need to convert them to factors!

# Create a design matrix including life history stage and its interaction with year
design_interaction <- model.matrix(~ year*life_history_stage, data = d_n$samples)  # No intercept
#Clean column names
colnames(design_interaction) <- c("Season1", "Season2", "Pup", "Season2_Pup")

# Define contrasts (compare seasons while accounting for life stage)
contr.matrix.interaction <- makeContrasts(
  Season1vsSeason2_adults = Season1 - Season2, 
  Season1vsSeason2_Pup = (Season1 + Pup) - (Season2 + Season2_Pup),
  PupvsAdult_Season1 = Pup,  
  PupvsAdult_Season2 = Pup + Season2_Pup,  
  Interaction = Season2_Pup, 
  levels = colnames(design_interaction)) 

# Run voom() to transform count data
vobj_interaction <- voom(d_n, design_interaction, plot=TRUE)

# Fit a random effect using duplicateCorrelation
dupcor_interaction <- duplicateCorrelation(vobj_interaction, design_interaction, block = d_n$samples$ID)

# Re-run voom with updated precision weights
vobj_interaction <- voom(d_n, design_interaction, plot=TRUE, 
               block=d_n$samples$ID, correlation=dupcor_interaction$consensus)

dupcor_interaction <- duplicateCorrelation(vobj_interaction, design_interaction, block = d_n$samples$ID)

#Estimate linear mixed model with a single variance component
vfit_interaction <- lmFit(vobj_interaction, design_interaction, block=d_n$samples$ID, correlation=dupcor_interaction$consensus)
vfit_interaction <- contrasts.fit(vfit_interaction, contrasts=contr.matrix.interaction)
# Fit Empirical Bayes for moderated t-statistics, empirical Bayes moderation is carried out by borrowing information across all the genes to obtain more precise estimates of gene-wise variability
efit_interaction <- eBayes(vfit_interaction)
topTable(efit_interaction, n=20)
plotSA(efit_interaction, main="Final model: Mean-variance trend")
plotMD(efit_interaction)
abline(h=0,col="darkgrey")

interaction_results <- topTable(efit_interaction, coef="Interaction", number=Inf, sort.by="P")

# Create a new column to categorize genes
interaction_results$Significance <- "Not Significant"
interaction_results$Significance[interaction_results$adj.P.Val < 0.05 & interaction_results$logFC >= 0.5] <- "Upregulated"
interaction_results$Significance[interaction_results$adj.P.Val < 0.05 & interaction_results$logFC <= -0.5] <- "Downregulated"

# Plot volcano plot
ggplot(interaction_results, aes(x = logFC, y = -log10(P.Value), color = Significance, size = Significance)) +
  geom_point(alpha = 0.7) +
  scale_color_manual(values = c("Upregulated" = "plum3", "Downregulated" = "cornflowerblue", "Not Significant" = "grey20")) +
  scale_size_manual(values = c("Upregulated" = 1.5, "Downregulated" = 1.5, "Not Significant" = 0.5)) +
  labs(title = "Differential Expression from Season x Life Stage Interaction",
       x = "Log2 Fold Change",
       y = "-Log10 P-value") +
  theme_classic()

# Difference between seasons in adults
Season1vsSeason2_adults_results <- topTable(efit_interaction, coef="Season1vsSeason2_adults", number=Inf, sort.by="P")

# Create a new column to categorize genes
Season1vsSeason2_adults_results$Significance <- "Not Significant"
Season1vsSeason2_adults_results$Significance[Season1vsSeason2_adults_results$adj.P.Val < 0.05 & Season1vsSeason2_adults_results$logFC >= 1] <- "Upregulated"
Season1vsSeason2_adults_results$Significance[Season1vsSeason2_adults_results$adj.P.Val < 0.05 & Season1vsSeason2_adults_results$logFC <= -1] <- "Downregulated"

# Plot volcano plot
S_adults <- ggplot(Season1vsSeason2_adults_results, aes(x = logFC, y = -log10(P.Value), color = Significance, size = Significance)) +
  geom_point(alpha = 0.7) +
  scale_color_manual(values = c("Upregulated" = "plum3", "Downregulated" = "cornflowerblue", "Not Significant" = "grey20")) +
  scale_size_manual(values = c("Upregulated" = 1.5, "Downregulated" = 1.5, "Not Significant" = 0.5)) +
  labs(title = "Differential Expression from Season1vsSeason2_adults",
       x = "Log2 Fold Change",
       y = "-Log10 P-value") +
  theme_classic()

# Difference between seasons in pups
Season1vsSeason2_Pup_results <- topTable(efit_interaction, coef="Season1vsSeason2_Pup", number=Inf, sort.by="P")

# Create a new column to categorize genes
Season1vsSeason2_Pup_results$Significance <- "Not Significant"
Season1vsSeason2_Pup_results$Significance[Season1vsSeason2_Pup_results$adj.P.Val < 0.05 & Season1vsSeason2_Pup_results$logFC >= 1] <- "Upregulated"
Season1vsSeason2_Pup_results$Significance[Season1vsSeason2_Pup_results$adj.P.Val < 0.05 & Season1vsSeason2_Pup_results$logFC <= -1] <- "Downregulated"

# Plot volcano plot
S_pups <- ggplot(Season1vsSeason2_Pup_results, aes(x = logFC, y = -log10(P.Value), color = Significance, size = Significance)) +
  geom_point(alpha = 0.7) +
  scale_color_manual(values = c("Upregulated" = "plum3", "Downregulated" = "cornflowerblue", "Not Significant" = "grey20")) +
  scale_size_manual(values = c("Upregulated" = 1.5, "Downregulated" = 1.5, "Not Significant" = 0.5)) +
  labs(title = "Differential Expression from Season1vsSeason2_Pup",
       x = "Log2 Fold Change",
       y = "-Log10 P-value") +
  theme_classic()

#Difference between life stage in season 1
PupvsAdult_Season1_results <- topTable(efit_interaction, coef="PupvsAdult_Season1", number=Inf, sort.by="P")

# Create a new column to categorize genes
PupvsAdult_Season1_results$Significance <- "Not Significant"
PupvsAdult_Season1_results$Significance[PupvsAdult_Season1_results$adj.P.Val < 0.05 & PupvsAdult_Season1_results$logFC >= 1] <- "Upregulated"
PupvsAdult_Season1_results$Significance[PupvsAdult_Season1_results$adj.P.Val < 0.05 & PupvsAdult_Season1_results$logFC <= -1] <- "Downregulated"

# Plot volcano plot
LS_Season1 <- ggplot(PupvsAdult_Season1_results, aes(x = logFC, y = -log10(P.Value), color = Significance, size = Significance)) +
  geom_point(alpha = 0.7) +
  scale_color_manual(values = c("Upregulated" = "plum3", "Downregulated" = "cornflowerblue", "Not Significant" = "grey20")) +
  scale_size_manual(values = c("Upregulated" = 1.5, "Downregulated" = 1.5, "Not Significant" = 0.5)) +
  labs(title = "Differential Expression from PupvsAdult_Season1",
       x = "Log2 Fold Change",
       y = "-Log10 P-value") +
  theme_classic()

#Difference between life stage in season 2
PupvsAdult_Season2_results <- topTable(efit_interaction, coef="PupvsAdult_Season2", number=Inf, sort.by="P")

# Create a new column to categorize genes
PupvsAdult_Season2_results$Significance <- "Not Significant"
PupvsAdult_Season2_results$Significance[PupvsAdult_Season2_results$adj.P.Val < 0.05 & PupvsAdult_Season2_results$logFC >= 1] <- "Upregulated"
PupvsAdult_Season2_results$Significance[PupvsAdult_Season2_results$adj.P.Val < 0.05 & PupvsAdult_Season2_results$logFC <= -1] <- "Downregulated"

# Plot volcano plot
LS_Season2 <- ggplot(PupvsAdult_Season2_results, aes(x = logFC, y = -log10(P.Value), color = Significance, size = Significance)) +
  geom_point(alpha = 0.7) +
  scale_color_manual(values = c("Upregulated" = "plum3", "Downregulated" = "cornflowerblue", "Not Significant" = "grey20")) +
  scale_size_manual(values = c("Upregulated" = 1.5, "Downregulated" = 1.5, "Not Significant" = 0.5)) +
  labs(title = "Differential Expression from PupvsAdult_Season2",
       x = "Log2 Fold Change",
       y = "-Log10 P-value") +
  theme_classic()
```

```{r}
#Bind plots together
library(cowplot)

DEG_interaction_all <- plot_grid(S_adults, S_pups, LS_Season1, LS_Season2)
# Save the density plot as a PNG file
ggsave(here::here("Plots","DEG_interaction_all.png"), plot = DEG_interaction_all, width = 12, height = 8, dpi = 600)
```
```{r}
#Simple interaction (limma manual 9.5.2)
#Create a design matrix including life history stage and its interaction with year
d_n$samples$y.lhs <- as.factor(paste(d_n$samples$year, d_n$samples$life_history_stage, sep = "."))
design_interaction <- model.matrix(~ 0+y.lhs, data = d_n$samples)  # No intercept
#Clean column names
colnames(design_interaction) <- c("Season1.mum", "Season1.pup", "Season2.mum", "Season2.pup")

# #voom() converts the read counts to log2-cpm, with associated weights, ready for linear modelling
vobj_interaction <- voom(d_n, design_interaction, plot=TRUE)

#Fit a random effect
dupcor_interaction <- duplicateCorrelation(vobj_interaction, design_interaction, block = d_n$samples$ID)
# #dupcor_interaction$consensus #the estimated intra individual correlation (0.09626666)

vobj_interaction = voom(d_n, design_interaction, plot=TRUE, 
                        block=d_n$samples$ID, correlation=dupcor_interaction$consensus)
# #update the correlation for the new voom weights
dupcor_interaction <- duplicateCorrelation(vobj_interaction, design_interaction, block = d_n$samples$ID)
# #dupcor_interaction$consensus #the estimated intra individual correlation (0.09627793)
# 
# #save dupcor_y
# saveRDS(dupcor_y, file = here::here("Dupcor","dupcor_y.rds"))
#Load dupcor_y
# dupcor_y <- readRDS(here::here("Dupcor","dupcor_y.rds"))


#Estimate linear mixed model with a single variance component
vfit_interaction <- lmFit(vobj_interaction, design_interaction, block=d_n$samples$ID, correlation=dupcor_interaction$consensus)

#Fit the contrasts we are interested in
cont.matrix.interaction <- makeContrasts(
  SeasonalAdult = Season1.mum - Season2.mum, #which genes in adults are DE among seasons
  SeasonalPup = Season1.pup - Season2.pup,  #which genes in pups are DE among seasons
  Adultvspupseason1 = Season1.mum - Season1.pup, #which genes in season 1 are DE among life stages
  Adultvspupseason2 = Season2.mum - Season2.pup, #which genes in season 2 are DE among life stages
  Interaction = (Season1.mum - Season1.pup)-(Season2.mum - Season2.pup), #which genes respond differently in pups compared to adults 
  levels = colnames(design_interaction)
)

vfit_interaction <- contrasts.fit(vfit_interaction, contrasts=cont.matrix.interaction)
# Fit Empirical Bayes for moderated t-statistics, empirical Bayes moderation is carried out by borrowing information across all the genes to obtain more precise estimates of gene-wise variability
efit_interaction <- eBayes(vfit_interaction)
topTable(efit_interaction, n=20)
plotSA(efit_interaction, main="Final model: Mean-variance trend")
plotMD(efit_interaction)
abline(h=0,col="darkgrey")

#adjusted p-value cutoff that is set at 5% by default.
efit_interaction$F
#head(efit_y$F.p.value) #pval of the moderated F-statistics (equivalent to one-way ANOVA), it combines all contrast, so in this case it is the same as the t-statistic
#head(efit_y$p.value) #same
summary(decideTests(efit_interaction, adjust.method="fdr"))

tfit_interaction <- treat(vfit_interaction, lfc=lfc_half) 
topTreat(tfit_interaction)
nrow(tfit_interaction)
dt_interaction <- decideTests(tfit_interaction, adjust.method="fdr")
summary(dt_interaction) 
```

```{r}
#Simple interaction (limma manual 9.5.2)
#Create a design matrix including life history stage and its interaction with year
d_n$samples$y.colony <- as.factor(paste(d_n$samples$year, d_n$samples$colony, sep = "."))
design_interaction2 <- model.matrix(~ 0+y.colony, data = d_n$samples)  # No intercept
#Clean column names
colnames(design_interaction2) <- c("Season1.FWB", "Season1.SSB", "Season2.FWB", "Season2.SSB")

# #voom() converts the read counts to log2-cpm, with associated weights, ready for linear modelling
vobj_interaction2 <- voom(d_n, design_interaction2, plot=TRUE)

#Fit a random effect
dupcor_interaction2 <- duplicateCorrelation(vobj_interaction2, design_interaction2, block = d_n$samples$ID)
# #dupcor_interaction$consensus #the estimated intra individual correlation (0.09626666)

vobj_interaction2 = voom(d_n, design_interaction2, plot=TRUE, 
                        block=d_n$samples$ID, correlation=dupcor_interaction2$consensus)
# #update the correlation for the new voom weights
dupcor_interaction2 <- duplicateCorrelation(vobj_interaction2, design_interaction2, block = d_n$samples$ID)
# #dupcor_interaction$consensus #the estimated intra individual correlation (0.09627793)
# 
# #save dupcor_y
# saveRDS(dupcor_y, file = here::here("Dupcor","dupcor_y.rds"))
#Load dupcor_y
# dupcor_y <- readRDS(here::here("Dupcor","dupcor_y.rds"))


#Estimate linear mixed model with a single variance component
vfit_interaction2 <- lmFit(vobj_interaction2, design_interaction2, block=d_n$samples$ID, correlation=dupcor_interaction2$consensus)

#Fit the contrasts we are interested in
cont.matrix.interaction2 <- makeContrasts(
  SeasonalFWB = Season1.FWB - Season2.FWB, #which genes on FWB are DE among seasons
  SeasonalSSB = Season1.SSB - Season2.SSB,  #which genes on SSB are DE among seasons
  FWBvsSSBseason1 = Season1.FWB - Season1.SSB, #which genes in season 1 are DE among colonies
  FWBvsSSBseason2 = Season2.FWB - Season2.SSB, #which genes in season 2 are DE among colonies
  Interaction = (Season1.FWB - Season1.SSB)-(Season2.FWB - Season2.SSB), #which genes respond differently in SSB compared to FWB
  levels = colnames(design_interaction2)
)

vfit_interaction2 <- contrasts.fit(vfit_interaction2, contrasts=cont.matrix.interaction2)
# Fit Empirical Bayes for moderated t-statistics, empirical Bayes moderation is carried out by borrowing information across all the genes to obtain more precise estimates of gene-wise variability
efit_interaction2 <- eBayes(vfit_interaction2)
topTable(efit_interaction2, n=20)
plotSA(efit_interaction2, main="Final model: Mean-variance trend")
plotMD(efit_interaction2)
abline(h=0,col="darkgrey")

#adjusted p-value cutoff that is set at 5% by default.
efit_interaction2$F
#head(efit_y$F.p.value) #pval of the moderated F-statistics (equivalent to one-way ANOVA), it combines all contrast, so in this case it is the same as the t-statistic
#head(efit_y$p.value) #same
summary(decideTests(efit_interaction2, adjust.method="fdr"))

tfit_interaction2 <- treat(vfit_interaction2, lfc=lfc_half) 
topTreat(tfit_interaction2)
nrow(tfit_interaction2)
dt_interaction2 <- decideTests(tfit_interaction2, adjust.method="fdr")
summary(dt_interaction2) 
```