---
title: "Gene expression project: GOrilla"
subtitle: "Analysis script"
author: "Bernice Sepers & Ane Liv Berthelsen"

format:
  html: 
  #pdf: 
    papersize: "a4paper"
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    number-sections: FALSE
    documentclass: article
    geometry:
      - inner=3cm
      - outer=3cm
      - top=2cm
      - bottom=3cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    fig-pos: 'h'
    fig-cap-location: bottom
    tbl-cap-location: top
editor: visual
date: 11/20/2023
mainfont: Times New Roman
---
# GOterms from GOrilla

```{r}
#Load in GOterms from GOrilla
library(readxl)
file.list <- list.files(path = here("GOterms_GOrilla"), pattern = "\\.xlsx$", full.names = T)

#for loop to load excel files in as data frames
for (file in file.list) {
  df_name <- tools::file_path_sans_ext(basename(file))
  assign(df_name, read_excel(file))}

#Remove non-significant terms
GOrilla_names <- c("TP_UP", "TP_DOWN", "LHS_UP", "LHS_DOWN", "I_TP_PUP_UP", "I_TP_PUP_DOWN", "I_TP_MUM_UP", "I_TP_MUM_DOWN", "I_I_UP", "I_I_DOWN")

for (name in GOrilla_names) {
  df <- get(name) 
  subset <- subset(df, as.numeric(`FDR q-value`) > 0.05)  
  assign(paste0( "GOrilla_", name), subset) 
}

#Remove unnecessary files
rm("TP_UP", "TP_DOWN", "LHS_UP", "LHS_DOWN", "I_TP_PUP_UP", "I_TP_PUP_DOWN", "I_TP_MUM_UP", "I_TP_MUM_DOWN", "I_I_UP", "I_I_DOWN", "subset", "df", "GOrilla_names", "file.list", "name", "df_name", "file")
```

### Similarity matrices

```{r}
GOrilla_names <- c(
  "GOrilla_TP_UP", "GOrilla_TP_DOWN", "GOrilla_LHS_UP", "GOrilla_LHS_DOWN",
  "GOrilla_I_TP_PUP_UP", "GOrilla_I_TP_PUP_DOWN", "GOrilla_I_TP_MUM_UP", 
  "GOrilla_I_TP_MUM_DOWN", "GOrilla_I_I_UP", "GOrilla_I_I_DOWN")

#calculate similarity matrix for each file
sim_matrices <- setNames(
  lapply(mget(GOrilla_names), function(df) {
    calculateSimMatrix(df$`GO term`, orgdb = "org.Hs.eg.db", ont = "BP", method = "Rel")
  }),
  GOrilla_names
)
```

### Reduce terms

```{r}
reduced_terms_list <- list()

for (name in GOrilla_names) {
  if (!exists(name)) {
    message(paste("Skipping", name, "- object does not exist"))
    reduced_terms_list[[name]] <- NULL
    next
  }

  df <- get(name)
  simMatrix <- sim_matrices[[name]]

  if (!is.data.frame(df)) {
    message(paste("Skipping", name, "- not a valid data frame"))
    reduced_terms_list[[name]] <- NULL
    next
  }

  if (!is.matrix(simMatrix) || any(is.na(simMatrix)) || nrow(simMatrix) < 2) {
    message(paste("Skipping", name, "- similarity matrix is invalid or too small"))
    reduced_terms_list[[name]] <- NULL
    next
  }

  # Ensure names align
  if (!"GO term" %in% colnames(df) || !"FDR q-value" %in% colnames(df)) {
    message(paste("Skipping", name, "- required columns not found"))
    reduced_terms_list[[name]] <- NULL
    next
  }

  scores <- -log10(as.numeric(df$`FDR q-value`))
  names(scores) <- df$`GO term`

  # Filter to only the terms in the similarity matrix
  common_terms <- intersect(names(scores), rownames(simMatrix))
  scores <- scores[common_terms]
  simMatrix_filtered <- simMatrix[common_terms, common_terms]

  if (length(common_terms) < 2) {
    message(paste("Skipping", name, "- fewer than 2 overlapping GO terms"))
    reduced_terms_list[[name]] <- NULL
    next
  }

  reduced_terms <- reduceSimMatrix(simMatrix_filtered, scores = scores, threshold = 0.7, orgdb = "org.Hs.eg.db")
  reduced_terms_list[[name]] <- reduced_terms
}
```

### Heatmaps

```{r}
HP_GOrilla_TP_DOWN <- heatmapPlot(sim_matrices$GOrilla_TP_DOWN,
                                  reduced_terms_list$GOrilla_TP_DOWN,
                                  annotateParent=TRUE,
                                  annotationLabel="parentTerm",
                                  fontsize=6,
                                  main = "Time Point (Downregulated) (GOrilla)")

HP_GOrilla_LHS_UP <- heatmapPlot(sim_matrices$GOrilla_LHS_UP,
                                  reduced_terms_list$GOrilla_LHS_UP,
                                  annotateParent=TRUE,
                                  annotationLabel="parentTerm",
                                  fontsize=6,
                                 main = "Life history stage (Upregulated) (GOrilla)")

HP_GOrilla_LHS_DOWN <- heatmapPlot(sim_matrices$GOrilla_LHS_DOWN,
                                  reduced_terms_list$GOrilla_LHS_DOWN,
                                  annotateParent=TRUE,
                                  annotationLabel="parentTerm",
                                  fontsize=6,
                                  main = "Life history stage (Downregulated) (GOrilla)")

plot_grid(HP_GOrilla_LHS_UP$gtable, HP_GOrilla_LHS_DOWN$gtable)
```

### Scatterplot

```{r}
SP_GOrilla_TP_DOWN <- scatterPlot(sim_matrices$GOrilla_TP_DOWN, reduced_terms_list$GOrilla_TP_DOWN) + 
  theme_classic() + 
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Time point: downregulated (GOrilla)") 

ggsave(here::here("Plots","SP_GOrilla_TP_DOWN.png"), plot = SP_GOrilla_TP_DOWN, width = 4.5, height = 5, dpi = 600)

SP_GOrilla_LHS_UP <- scatterPlot(sim_matrices$GOrilla_LHS_UP, reduced_terms_list$GOrilla_LHS_UP) + 
  theme_classic() + 
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Life history stage: upregulated (GOrilla)") 

SP_GOrilla_LHS_DOWN <- scatterPlot(sim_matrices$GOrilla_TP_DOWN, reduced_terms_list$GOrilla_TP_DOWN) + 
  theme_classic() + 
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Life history stage: downregulated (GOrilla)") 

SP_LHS_GOrilla <- plot_grid(SP_GOrilla_LHS_UP, SP_GOrilla_LHS_DOWN)
ggsave(here::here("Plots","SP_LHS_GOrilla.png"), plot = SP_LHS_GOrilla, width = 9, height = 5, dpi = 600)

#Interaction
SP_GOrilla_I_TP_PUP_UP <- scatterPlot(sim_matrices$GOrilla_I_TP_PUP_UP, reduced_terms_list$GOrilla_I_TP_PUP_UP) + 
  theme_classic() + 
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Time point: upregulated (Pup)")

SP_GOrilla_I_TP_PUP_DOWN <- scatterPlot(sim_matrices$GOrilla_I_TP_PUP_DOWN, reduced_terms_list$GOrilla_I_TP_PUP_DOWN) + 
  theme_classic() + 
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Time point: downregulated (Pup)") 

SP_GOrilla_I_TP_MUM_UP <- scatterPlot(sim_matrices$GOrilla_I_TP_MUM_UP, reduced_terms_list$GOrilla_I_TP_MUM_UP) + 
  theme_classic() + 
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Time point: upregulated (Mother)") 

SP_GOrilla_I_TP_MUM_DOWN <- scatterPlot(sim_matrices$GOrilla_I_TP_MUM_DOWN, reduced_terms_list$GOrilla_I_TP_MUM_DOWN) + 
  theme_classic() + 
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Time point: downregulated (Mother)") 

SP_GOrilla_I_I_UP <- scatterPlot(sim_matrices$GOrilla_I_I_UP, reduced_terms_list$GOrilla_I_I_UP) + 
  theme_classic() +
  xlim(c(-0.75,0.75)) + 
  ylim(c(-0.75,0.75)) +
  xlab("Semantic space x") +
  ylab("Semantic space y") +
  ggtitle("Interaction: Upregulated") 

#SP_GOrilla_I_I_DOWN <- scatterPlot(sim_matrices$GOrilla_I_I_DOWN, reduced_terms_list$GOrilla_I_I_DOWN) + theme_classic() + 
#  ggtitle("Interaction: Downregulated interaction") 
#Not enough info

SP_Interaction_GOrilla <- plot_grid(SP_GOrilla_I_TP_PUP_UP, SP_GOrilla_I_TP_PUP_DOWN, NULL, SP_GOrilla_I_TP_MUM_UP, SP_GOrilla_I_TP_MUM_DOWN, SP_GOrilla_I_I_UP)

title <- ggdraw() + 
  draw_label(
    "Interaction (GOrilla)",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

SP_Interaction_GOrilla_title <- plot_grid(title, SP_Interaction_GOrilla,
          ncol = 1,
          rel_heights = c(0.1, 1))

ggsave(here::here("Plots","SP_Interaction_GOrilla_title.png"), plot = SP_Interaction_GOrilla_title, width = 13.5, height = 10, dpi = 600)
```
